package cn.lt.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.json.JSONObject;

import java.io.Serializable;

import cn.lt.android.entity.DownloadEntity;

/**
 * Entity mapped to table "APP_ENTITY".
 */
public class AppEntity extends DownloadEntity implements Serializable, Comparable<AppEntity> {

    private Long id;
    private String packageName;
    private String name;
    private String alias;
    private String downloadUrl;
    private String savePath;
    private String iconUrl;
    private String packageSize;
    private String apps_type;
    private Long apps_startDownloadTime;
    private Long apps_endDownloadTime;
    private Boolean lackofmemory = false;
    private String package_md5;
    private String version_code;
    private String version_name;
    private String corner_url;
    private String reviews;
    private String created_at;
    private String download_count;
    private String description;
    private String category;
    private Boolean isAD = false;
    private Boolean isOrderWifiDownload = false;
    private Boolean isAppAutoUpgrade = false;
    private Boolean canReplace = false;
    private String adMold;
    public int netType;
    private String reportData;

    public Long mSetUpTime;
    public Long lastClickTime;

    public String resource_type;
    public String word;

    private Long errorType;

    public boolean isOrderWifiContinue() {
        return isOrderWifiContinue;
    }

    public void setOrderWifiContinue(boolean orderWifiContinue) {
        isOrderWifiContinue = orderWifiContinue;
    }

    private boolean isOrderWifiContinue = false;

    public int getIsOrderWifiUpgrade() {
        return isOrderWifiUpgrade;
    }

    public void setIsOrderWifiUpgrade(int isOrderWifiUpgrade) {
        this.isOrderWifiUpgrade = isOrderWifiUpgrade;
    }

    private int isOrderWifiUpgrade;

    public AppEntity() {
    }

    public AppEntity(Long id) {
        this.id = id;
    }

    public AppEntity(Long id, String packageName, String name, String alias, String downloadUrl, String savePath, String iconUrl, String packageSize, String apps_type, Long apps_startDownloadTime, Long apps_endDownloadTime, Boolean lackofmemory, String package_md5, String version_code, String version_name, String corner_url, String reviews, String created_at, String download_count, String description, String category, Boolean isAD, Boolean isOrderWifiDownload, Boolean isAppAutoUpgrade, Boolean canReplace, String adMold, String reportData,Long errorType) {
        this.id = id;
        this.packageName = packageName;
        this.name = name;
        this.alias = alias;
        this.downloadUrl = downloadUrl;
        this.savePath = savePath;
        this.iconUrl = iconUrl;
        this.packageSize = packageSize;
        this.apps_type = apps_type;
        this.apps_startDownloadTime = apps_startDownloadTime;
        this.apps_endDownloadTime = apps_endDownloadTime;
        this.lackofmemory = lackofmemory;
        this.package_md5 = package_md5;
        this.version_code = version_code;
        this.version_name = version_name;
        this.corner_url = corner_url;
        this.reviews = reviews;
        this.created_at = created_at;
        this.download_count = download_count;
        this.description = description;
        this.category = category;
        this.isAD = isAD;
        this.isOrderWifiDownload = isOrderWifiDownload;
        this.isAppAutoUpgrade = isAppAutoUpgrade;
        this.canReplace = canReplace;
        this.adMold = adMold;
        this.reportData = reportData;
        this.errorType = errorType;
    }

    public long getId() {
        return id;
    }

    public String getAppClientId() {
        if (isAdData()) {
            return packageName;
        } else {
            return getId() + "";
        }
    }

    public boolean isAdData() {
        if (getId() <= 0) {
            return true;
        }
        return false;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public String getDownloadUrl() {
        return downloadUrl;
    }

    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    public String getSavePath() {
        return savePath;
    }

    public void setSavePath(String savePath) {
        this.savePath = savePath;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getPackageSize() {
        return packageSize;
    }

    public void setPackageSize(String packageSize) {
        this.packageSize = packageSize;
    }

    public String getApps_type() {
        return apps_type;
    }

    public void setApps_type(String apps_type) {
        this.apps_type = apps_type;
    }

    public Long getApps_startDownloadTime() {
        return apps_startDownloadTime;
    }

    public void setApps_startDownloadTime(Long apps_startDownloadTime) {
        this.apps_startDownloadTime = apps_startDownloadTime;
    }

    public Long getApps_endDownloadTime() {
        return apps_endDownloadTime;
    }

    public void setApps_endDownloadTime(Long apps_endDownloadTime) {
        this.apps_endDownloadTime = apps_endDownloadTime;
    }

    public Boolean getLackofmemory() {
        return lackofmemory == null ? false : lackofmemory;
    }

    public void setLackofmemory(Boolean lackofmemory) {
        this.lackofmemory = lackofmemory;
    }

    public String getPackage_md5() {
        return package_md5;
    }

    public void setPackage_md5(String package_md5) {
        this.package_md5 = package_md5;
    }

    public String getVersion_code() {
        return version_code;
    }

    public void setVersion_code(String version_code) {
        this.version_code = version_code;
    }

    public String getVersion_name() {
        return version_name;
    }

    public void setVersion_name(String version_name) {
        this.version_name = version_name;
    }

    public String getCorner_url() {
        return corner_url;
    }

    public void setCorner_url(String corner_url) {
        this.corner_url = corner_url;
    }

    public String getReviews() {
        return reviews;
    }

    public void setReviews(String reviews) {
        this.reviews = reviews;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getDownload_count() {
        return download_count;
    }

    public void setDownload_count(String download_count) {
        this.download_count = download_count;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Boolean getIsAD() {
        return isAD == null ? false : isAD;
    }

    public void setIsAD(Boolean isAD) {
        this.isAD = isAD;
    }

    public Boolean getIsOrderWifiDownload() {
        return isOrderWifiDownload == null ? false : isOrderWifiDownload;
    }

    public void setIsOrderWifiDownload(Boolean isOrderWifiDownload) {
        this.isOrderWifiDownload = isOrderWifiDownload;
    }

    public Boolean getIsAppAutoUpgrade() {
        return isAppAutoUpgrade == null ? false : isAppAutoUpgrade;
    }

    public void setIsAppAutoUpgrade(Boolean isAppAutoUpgrade) {
        this.isAppAutoUpgrade = isAppAutoUpgrade;
    }

    public Boolean canReplace() {
        return canReplace;
    }

    public void setCanReplace(Boolean canReplace) {
        this.canReplace = canReplace;
    }

    public String getAdMold() {
        return adMold == null ? "" : adMold;
    }

    public void setAdMold(String adMold) {
        this.adMold = adMold;
    }

    public String getReportData() {
        return reportData;
    }

    public void setReportData(String reportData) {
        this.reportData = reportData;
    }

    public void setReportDataJsonObj(JSONObject jsonObj) {
        if (jsonObj != null) {
            this.reportData = jsonObj.toString();
        }
    }

    public JSONObject getReportDataJsonObj() {
        try {
            return new JSONObject(this.reportData);
        } catch (Exception e) {
            e.printStackTrace();
        }

        return null;
    }

    @Override
    public int compareTo(AppEntity another) {
        long a = another.getApps_startDownloadTime();
        long b = this.getApps_startDownloadTime();
        return String.valueOf(a).compareTo(String.valueOf(b));
    }

    public Long getErrorType() {
        return errorType == null ? 0 : errorType;
    }

    public void setErrorType(Long errorType) {
        this.errorType = errorType;
    }
}
