package cn.lt.android.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appEntityDaoConfig;
    private final DaoConfig searchHistoryEntityDaoConfig;
    private final DaoConfig ignoreUpgradeAppEntityDaoConfig;
    private final DaoConfig statisticsEntityDaoConfig;
	 private final DaoConfig loginHistoryEntityDaoConfig;

    private final DaoConfig retryStatisticsEntityDaoConfig;

    private final DaoConfig userEntityDaoConfig;

    private final RetryStatisticsEntityDao retryStatisticsEntityDao;
    private final AppEntityDao appEntityDao;
    private final SearchHistoryEntityDao searchHistoryEntityDao;
    private final IgnoreUpgradeAppEntityDao ignoreUpgradeAppEntityDao;
    private final StatisticsEntityDao statisticsEntityDao;
	private final LoginHistoryEntityDao loginHistoryEntityDao;

    private final UserEntityDao userEntityDao;
    private final DaoConfig wakeTaskEntityDaoConfig;
    private final WakeTaskEntityDao wakeTaskEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appEntityDaoConfig = daoConfigMap.get(AppEntityDao.class).clone();
        appEntityDaoConfig.initIdentityScope(type);

        searchHistoryEntityDaoConfig = daoConfigMap.get(SearchHistoryEntityDao.class).clone();
        searchHistoryEntityDaoConfig.initIdentityScope(type);

        ignoreUpgradeAppEntityDaoConfig = daoConfigMap.get(IgnoreUpgradeAppEntityDao.class).clone();
        ignoreUpgradeAppEntityDaoConfig.initIdentityScope(type);

        statisticsEntityDaoConfig = daoConfigMap.get(StatisticsEntityDao.class).clone();
        statisticsEntityDaoConfig.initIdentityScope(type);

        loginHistoryEntityDaoConfig = daoConfigMap.get(LoginHistoryEntityDao.class).clone();
        loginHistoryEntityDaoConfig.initIdentityScope(type);

        retryStatisticsEntityDaoConfig = daoConfigMap.get(RetryStatisticsEntityDao.class).clone();
        retryStatisticsEntityDaoConfig.initIdentityScope(type);


        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        wakeTaskEntityDaoConfig = daoConfigMap.get(WakeTaskEntityDao.class).clone();
        wakeTaskEntityDaoConfig.initIdentityScope(type);

        appEntityDao = new AppEntityDao(appEntityDaoConfig, this);
        searchHistoryEntityDao = new SearchHistoryEntityDao(searchHistoryEntityDaoConfig, this);
        ignoreUpgradeAppEntityDao = new IgnoreUpgradeAppEntityDao(ignoreUpgradeAppEntityDaoConfig, this);
        statisticsEntityDao = new StatisticsEntityDao(statisticsEntityDaoConfig, this);
        loginHistoryEntityDao = new LoginHistoryEntityDao(loginHistoryEntityDaoConfig, this);
        retryStatisticsEntityDao = new RetryStatisticsEntityDao(retryStatisticsEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        wakeTaskEntityDao = new WakeTaskEntityDao(wakeTaskEntityDaoConfig, this);

        registerDao(AppEntity.class, appEntityDao);
        registerDao(SearchHistoryEntity.class, searchHistoryEntityDao);
        registerDao(IgnoreUpgradeAppEntity.class, ignoreUpgradeAppEntityDao);
        registerDao(StatisticsEntity.class, statisticsEntityDao);
        registerDao(LoginHistoryEntity.class, loginHistoryEntityDao);
        registerDao(RetryStatisticsEntity.class, retryStatisticsEntityDao);
        registerDao(UserEntity.class, userEntityDao);
        registerDao(WakeTaskEntity.class, wakeTaskEntityDao);

    }

    public void clear() {
        appEntityDaoConfig.getIdentityScope().clear();
        searchHistoryEntityDaoConfig.getIdentityScope().clear();
        ignoreUpgradeAppEntityDaoConfig.getIdentityScope().clear();
        statisticsEntityDaoConfig.getIdentityScope().clear();
		loginHistoryEntityDaoConfig.getIdentityScope().clear();
        retryStatisticsEntityDaoConfig.getIdentityScope().clear();
        userEntityDaoConfig.getIdentityScope().clear();
        wakeTaskEntityDaoConfig.getIdentityScope().clear();
    }

    public AppEntityDao getAppEntityDao() {
        return appEntityDao;
    }

    public SearchHistoryEntityDao getSearchHistoryEntityDao() {
        return searchHistoryEntityDao;
    }

    public IgnoreUpgradeAppEntityDao getIgnoreUpgradeAppEntityDao() {
        return ignoreUpgradeAppEntityDao;
    }

    public StatisticsEntityDao getStatisticsEntityDao() {
        return statisticsEntityDao;
    }

	public LoginHistoryEntityDao getLoginHistoryEntityDao() {
        return loginHistoryEntityDao;
    }

    public RetryStatisticsEntityDao getRetryStatisticsEntityDao() {
        return retryStatisticsEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public WakeTaskEntityDao getWakeTaskEntityDao() {
        return wakeTaskEntityDao;
    }
}
