package cn.lt.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IGNORE_UPGRADE_APP_ENTITY".
 */
public class IgnoreUpgradeAppEntity {

    private Long id;
    private String name;
    private String packageName;
    private String versionName;

    public IgnoreUpgradeAppEntity() {
    }

    public IgnoreUpgradeAppEntity(Long id) {
        this.id = id;
    }

    public IgnoreUpgradeAppEntity(Long id, String name, String packageName, String versionName) {
        this.id = id;
        this.name = name;
        this.packageName = packageName;
        this.versionName = versionName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getVersionName() {
        return versionName;
    }

    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

}
