package cn.lt.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOGIN_HISTORY_ENTITY".
 */
public class LoginHistoryEntity {

    private Long id;
    private String avatar;
    private String mobile;
    private String email;
    private String token;
    private Long userId;
    private String nickName;

    public LoginHistoryEntity() {
    }

    public LoginHistoryEntity(Long id) {
        this.id = id;
    }

    public LoginHistoryEntity(Long id, String avatar, String mobile, String email, String token, Long userId, String nickName) {
        this.id = id;
        this.avatar = avatar;
        this.mobile = mobile;
        this.email = email;
        this.token = token;
        this.userId = userId;
        this.nickName = nickName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

}
