package cn.lt.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RETRY_STATISTICS_ENTITY".
 */
public class RetryStatisticsEntity {

    private Long id;
    private String mUploadFailureDataByJsonString;

    public RetryStatisticsEntity() {
    }

    public RetryStatisticsEntity(Long id) {
        this.id = id;
    }

    public RetryStatisticsEntity(Long id, String mUploadFailureDataByJsonString) {
        this.id = id;
        this.mUploadFailureDataByJsonString = mUploadFailureDataByJsonString;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMUploadFailureDataByJsonString() {
        return mUploadFailureDataByJsonString;
    }

    public void setMUploadFailureDataByJsonString(String mUploadFailureDataByJsonString) {
        this.mUploadFailureDataByJsonString = mUploadFailureDataByJsonString;
    }

}
