package cn.lt.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STATISTICS_ENTITY".
 */
public class StatisticsEntity implements Cloneable{

    private Long id;
    private String mGameID;
    private String mPkgName;
    private String mActionType;
    private String mDownloadType;
    private String mRemark;
    private String mPage;
    private String mPageID;
    private String mDownloadMode;
    private String mInstallMode;
    private String mInstallWay;
    private String mAdType;
    private Integer mCount;
    private Double mTimeMillis;
    private String from_page;
    private String resource_type;
    private String word;
    private String from_id;
    private Integer P1;
    private Integer P2;

    public StatisticsEntity() {
    }

    public StatisticsEntity(Long id) {
        this.id = id;
    }

    public StatisticsEntity(Long id, String mGameID, String mPkgName, String mActionType, String mDownloadType, String mRemark, String mPage, String mPageID, String mDownloadMode, String mInstallMode, String mInstallWay, String mAdType, Integer mCount, Double mTimeMillis, String from_page, String resource_type, String word, String from_id, Integer P1, Integer P2) {
        this.id = id;
        this.mGameID = mGameID;
        this.mPkgName = mPkgName;
        this.mActionType = mActionType;
        this.mDownloadType = mDownloadType;
        this.mRemark = mRemark;
        this.mPage = mPage;
        this.mPageID = mPageID;
        this.mDownloadMode = mDownloadMode;
        this.mInstallMode = mInstallMode;
        this.mInstallWay = mInstallWay;
        this.mAdType = mAdType;
        this.mCount = mCount;
        this.mTimeMillis = mTimeMillis;
        this.from_page = from_page;
        this.resource_type = resource_type;
        this.word = word;
        this.from_id = from_id;
        this.P1 = P1;
        this.P2 = P2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMGameID() {
        return mGameID;
    }

    public void setMGameID(String mGameID) {
        this.mGameID = mGameID;
    }

    public String getMPkgName() {
        return mPkgName;
    }

    public void setMPkgName(String mPkgName) {
        this.mPkgName = mPkgName;
    }

    public String getMActionType() {
        return mActionType;
    }

    public void setMActionType(String mActionType) {
        this.mActionType = mActionType;
    }

    public String getMDownloadType() {
        return mDownloadType;
    }

    public void setMDownloadType(String mDownloadType) {
        this.mDownloadType = mDownloadType;
    }

    public String getMRemark() {
        return mRemark;
    }

    public void setMRemark(String mRemark) {
        this.mRemark = mRemark;
    }

    public String getMPage() {
        return mPage;
    }

    public void setMPage(String mPage) {
        this.mPage = mPage;
    }

    public String getMPageID() {
        return mPageID;
    }

    public void setMPageID(String mPageID) {
        this.mPageID = mPageID;
    }

    public String getMDownloadMode() {
        return mDownloadMode;
    }

    public void setMDownloadMode(String mDownloadMode) {
        this.mDownloadMode = mDownloadMode;
    }

    public String getMInstallMode() {
        return mInstallMode;
    }

    public void setMInstallMode(String mInstallMode) {
        this.mInstallMode = mInstallMode;
    }

    public String getMInstallWay() {
        return mInstallWay;
    }

    public void setMInstallWay(String mInstallWay) {
        this.mInstallWay = mInstallWay;
    }

    public String getMAdType() {
        return mAdType;
    }

    public void setMAdType(String mAdType) {
        this.mAdType = mAdType;
    }

    public Integer getMCount() {
        return mCount;
    }

    public void setMCount(Integer mCount) {
        this.mCount = mCount;
    }

    public Double getMTimeMillis() {
        return mTimeMillis;
    }

    public void setMTimeMillis(Double mTimeMillis) {
        this.mTimeMillis = mTimeMillis;
    }

    public String getFrom_page() {
        return from_page;
    }

    public void setFrom_page(String from_page) {
        this.from_page = from_page;
    }

    public String getResource_type() {
        return resource_type;
    }

    public void setResource_type(String resource_type) {
        this.resource_type = resource_type;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getFrom_id() {
        return from_id;
    }

    public void setFrom_id(String from_id) {
        this.from_id = from_id;
    }

    public Integer getP1() {
        return P1;
    }

    public void setP1(Integer P1) {
        this.P1 = P1;
    }

    public Integer getP2() {
        return P2;
    }

    public void setP2(Integer P2) {
        this.P2 = P2;
    }

    @Override
    public StatisticsEntity clone() throws CloneNotSupportedException {
        return (StatisticsEntity)super.clone();
    }
}
