package cn.lt.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "WAKE_TASK_ENTITY".
 */
public class WakeTaskEntity implements Serializable{

    private Long id;
    private Integer task_id;
    private String type;
    private String package_name;
    private Long user_cycle;
    private Long task_cycle;
    private Integer show_type;
    private String title;
    private String sub_title;
    private String image;
    private String action_name;
    private String class_name;
    private String deep_link;
    private String extra;
    private Long lastExecuteTime;
    private Integer executeTimes;
    private Integer show_time;
    private String jump_type;

    public WakeTaskEntity() {
    }

    public WakeTaskEntity(Long id) {
        this.id = id;
    }

    public WakeTaskEntity(Long id, Integer task_id, String type, String package_name, Long user_cycle, Long task_cycle, Integer show_type, String title, String sub_title, String image, String action_name, String class_name, String deep_link, String extra, Long lastExecuteTime, Integer executeTimes, Integer show_time, String jump_type) {
        this.id = id;
        this.task_id = task_id;
        this.type = type;
        this.package_name = package_name;
        this.user_cycle = user_cycle;
        this.task_cycle = task_cycle;
        this.show_type = show_type;
        this.title = title;
        this.sub_title = sub_title;
        this.image = image;
        this.action_name = action_name;
        this.class_name = class_name;
        this.deep_link = deep_link;
        this.extra = extra;
        this.lastExecuteTime = lastExecuteTime;
        this.executeTimes = executeTimes;
        this.show_time = show_time;
        this.jump_type = jump_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTask_id() {
        return task_id;
    }

    public void setTask_id(Integer task_id) {
        this.task_id = task_id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPackage_name() {
        return package_name;
    }

    public void setPackage_name(String package_name) {
        this.package_name = package_name;
    }

    public Long getUser_cycle() {
        return user_cycle;
    }

    public void setUser_cycle(Long user_cycle) {
        this.user_cycle = user_cycle;
    }

    public Long getTask_cycle() {
        return task_cycle;
    }

    public void setTask_cycle(Long task_cycle) {
        this.task_cycle = task_cycle;
    }

    public Integer getShow_type() {
        return show_type;
    }

    public void setShow_type(Integer show_type) {
        this.show_type = show_type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSub_title() {
        return sub_title;
    }

    public void setSub_title(String sub_title) {
        this.sub_title = sub_title;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getAction_name() {
        return action_name;
    }

    public void setAction_name(String action_name) {
        this.action_name = action_name;
    }

    public String getClass_name() {
        return class_name;
    }

    public void setClass_name(String class_name) {
        this.class_name = class_name;
    }

    public String getDeep_link() {
        return deep_link;
    }

    public void setDeep_link(String deep_link) {
        this.deep_link = deep_link;
    }

    public String getExtra() {
        return extra;
    }

    public void setExtra(String extra) {
        this.extra = extra;
    }

    public Long getLastExecuteTime() {
        return lastExecuteTime;
    }

    public void setLastExecuteTime(Long lastExecuteTime) {
        this.lastExecuteTime = lastExecuteTime;
    }

    public Integer getExecuteTimes() {
        return executeTimes;
    }

    public void setExecuteTimes(Integer executeTimes) {
        this.executeTimes = executeTimes;
    }

    public Integer getShow_time() {
        return show_time;
    }

    public void setShow_time(Integer show_time) {
        this.show_time = show_time;
    }

    public String getJump_type() {
        return jump_type;
    }

    public void setJump_type(String jump_type) {
        this.jump_type = jump_type;
    }

}
