package cn.lt.android.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOGIN_HISTORY_ENTITY".
 */
public class LoginHistory {

    private Long id;
    private String avatar;
    private String mobile;
    private String email;

    public LoginHistory() {
    }

    public LoginHistory(Long id) {
        this.id = id;
    }

    public LoginHistory(Long id, String avatar, String mobile, String email) {
        this.id = id;
        this.avatar = avatar;
        this.mobile = mobile;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
